preset: symfony

enabled:
  - unalign_double_arrow
  - unalign_equals
  - newline_after_open_tag
  - ordered_use
  - long_array_syntax
  - php_unit_construct

disabled:
  - unalign_double_arrow
  - unalign_equals
  - phpdoc_align
